# Do not edit this file or it may not load correctly
# if you try to open it with the RSG Dialog Builder.

# Note: thisDir is defined by the Activator class when
#       this file gets exec'd

from rsg.rsgGui import *
from abaqusConstants import INTEGER, FLOAT
dialogBox = RsgDialog(title='Energy Dissipation Calculator', kernelModule='EDC2', kernelFunction='fEDC', includeApplyBtn=False, includeSeparator=True, okBtnText='OK', applyBtnText='Apply', execDir=thisDir)
RsgTabBook(name='TabBook_1', p='DialogBox', layout='0')
RsgTabItem(name='TabItem_3', p='TabBook_1', text='Part Selection')
RsgComboBox(name='ComboBox_2', p='TabItem_3', text='Part:', keyword='part', default='', comboType='MDB', repository='parts', rootText='Model:', rootKeyword='model', layout='HORIZONTAL')
RsgTabItem(name='TabItem_4', p='TabBook_1', text='Material toughness')
RsgComboBox(name='ComboBox_3', p='TabItem_4', text='Default Materials', keyword='mat', default='T800s/M21', comboType='STANDARD', repository='', rootText='', rootKeyword=None, layout='')
RsgListItem(p='ComboBox_3', text='T800s/M21')
RsgListItem(p='ComboBox_3', text='T300/920')
RsgListItem(p='ComboBox_3', text='T300/913')
RsgCheckButton(p='TabItem_4', text='Custom Material', keyword='cusMat', default=False)
RsgTextField(p='TabItem_4', fieldType='Integer', ncols=12, labelText='Interlaminar fracture toughness:', keyword='g0', default='0')
RsgTextField(p='TabItem_4', fieldType='String', ncols=12, labelText='Intralaminar fracture toughness:', keyword='g90', default='0')
RsgTabItem(name='TabItem_1', p='TabBook_1', text='Single Surface Fracture')
RsgCheckButton(p='TabItem_1', text='Calculate single fracture surface?', keyword='singlePlane', default=False)
RsgLabel(p='TabItem_1', text='Select Three Points (Nodes In Mesh) On Fracture Surface. (Do Not Select Duplicate Points)', useBoldFont=False)
RsgPickButton(p='TabItem_1', text='Point 1', keyword='coord1', prompt='Pick a point', entitiesToPick='MDB_MESH|NODES', numberToPick='ONE')
RsgPickButton(p='TabItem_1', text='Point 2', keyword='coord2', prompt='Pick a point', entitiesToPick='MDB_MESH|NODES', numberToPick='ONE')
RsgPickButton(p='TabItem_1', text='Point 3', keyword='coord3', prompt='Pick a point', entitiesToPick='MDB_MESH|NODES', numberToPick='ONE')
RsgLabel(p='TabItem_1', text='Refer To Diagram Below For Reference', useBoldFont=True)
RsgLabel(p='TabItem_1', text='Only one energy output will be given', useBoldFont=False)
RsgIcon(p='TabItem_1', fileName=r'diagram single surface.PNG')
RsgTabItem(name='TabItem_2', p='TabBook_1', text='Multi Surfaces Fractures')
RsgCheckButton(p='TabItem_2', text='Calculate multiple planes?', keyword='multiPlane', default=False)
RsgLabel(p='TabItem_2', text='Select only one axis', useBoldFont=False)
RsgCheckButton(p='TabItem_2', text='X-axis', keyword='xaxis', default=True)
RsgCheckButton(p='TabItem_2', text='Y-axis', keyword='yaxis', default=False)
RsgCheckButton(p='TabItem_2', text='Z-axis', keyword='zaxis', default=False)
RsgLabel(p='TabItem_2', text='Direction of axis perpendicular to desired fracture surfaces', useBoldFont=False)
RsgTextField(p='TabItem_2', fieldType='Integer', ncols=12, labelText='Number of fracture surfaces (N, Reference to diagram):', keyword='N', default='10')
RsgLabel(p='TabItem_2', text='Diagram Showing Planes Incrementing In The Z Axis If N Is 3', useBoldFont=True)
RsgLabel(p='TabItem_2', text='Surfaces Will Be Created From Negative To Positive Coordinates', useBoldFont=True)
RsgLabel(p='TabItem_2', text='Output of plot for energy with each coordinate will be given along with critical surface', useBoldFont=False)
RsgIcon(p='TabItem_2', fileName=r'abaqus diagram for multi plane.PNG')
dialogBox.show()